function escapePowerShellPath(absPath: string): string {
  return absPath.replace(/\\/g, '\\\\').replace(/'/g, "''");
}

export function buildWordPowerShellScript(absPath: string): string {
  const psPath = escapePowerShellPath(absPath);
  return [
    '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8',
    '$word = $null',
    '$doc = $null',
    'try {',
    '    $word = New-Object -ComObject Word.Application',
    '    $word.Visible = $false',
    '    $word.DisplayAlerts = 0',
    "    $doc = $word.Documents.Open('" + psPath + "', $false, $true, $false)",
    '    Start-Sleep -Seconds 1',
    '    $content = $doc.Content.Text',
    '    $pageCount = $doc.ComputeStatistics(2)',
    '    $wordCount = $doc.ComputeStatistics(0)',
    '    $charCount = $content.Length',
    '    Write-Output "STATS:$pageCount|$wordCount|$charCount"',
    '    Write-Output "TEXT_START"',
    '    Write-Output $content',
    '    Write-Output "TEXT_END"',
    '} catch {',
    '    Write-Error $_.Exception.Message',
    '    exit 1',
    '} finally {',
    '    if ($doc) {',
    '        $doc.Close([ref]$false)',
    '        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($doc) | Out-Null',
    '    }',
    '    if ($word) {',
    '        $word.Quit()',
    '        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($word) | Out-Null',
    '    }',
    '    [System.GC]::Collect()',
    '    [System.GC]::WaitForPendingFinalizers()',
    '}',
  ].join('\n');
}

export function buildPowerPointPowerShellScript(absPath: string): string {
  const psPath = escapePowerShellPath(absPath);
  const newline = '`n';
  return [
    '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8',
    '$ppt = $null',
    '$pres = $null',
    'try {',
    '    $ppt = New-Object -ComObject PowerPoint.Application',
    "    $pres = $ppt.Presentations.Open('" + psPath + "', -1, 0, 0)",
    '    Start-Sleep -Seconds 1',
    '    $slideCount = $pres.Slides.Count',
    '    $allText = ""',
    '    for ($i = 1; $i -le $slideCount; $i++) {',
    '        $slide = $pres.Slides.Item($i)',
    '        $allText += "' + newline + '--- Slide $i ---' + newline + '"',
    '        foreach ($shape in $slide.Shapes) {',
    '            try {',
    '                if ($shape.HasTextFrame -eq -1) {',
    '                    if ($shape.TextFrame.HasText -eq -1) {',
    '                        $text = $shape.TextFrame.TextRange.Text',
    '                        if ($text.Trim() -ne "") {',
    '                            $allText += $text + "' + newline + '"',
    '                        }',
    '                    }',
    '                }',
    '            } catch { }',
    '        }',
    '        try {',
    '            if ($slide.HasNotesPage -eq -1) {',
    '                foreach ($shape in $slide.NotesPage.Shapes) {',
    '                    if ($shape.HasTextFrame -eq -1) {',
    '                        if ($shape.TextFrame.HasText -eq -1) {',
    '                            $notesText = $shape.TextFrame.TextRange.Text',
    '                            if ($notesText.Trim() -ne "") {',
    '                                $allText += "' + newline + '--- Notes ---' + newline + '" + $notesText + "' + newline + '"',
    '                            }',
    '                        }',
    '                    }',
    '                }',
    '            }',
    '        } catch { }',
    '    }',
    '    Write-Output "STATS:$slideCount"',
    '    Write-Output "TEXT_START"',
    '    Write-Output $allText',
    '    Write-Output "TEXT_END"',
    '} catch {',
    '    Write-Error $_.Exception.Message',
    '    exit 1',
    '} finally {',
    '    if ($pres) {',
    '        $pres.Close()',
    '        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($pres) | Out-Null',
    '    }',
    '    if ($ppt) {',
    '        $ppt.Quit()',
    '        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($ppt) | Out-Null',
    '    }',
    '    [System.GC]::Collect()',
    '    [System.GC]::WaitForPendingFinalizers()',
    '}',
  ].join('\n');
}

export function buildExcelPowerShellScript(absPath: string): string {
  const psPath = escapePowerShellPath(absPath);
  const newline = '`n';
  return [
    '[Console]::OutputEncoding = [System.Text.Encoding]::UTF8',
    '$excel = $null',
    '$wb = $null',
    'try {',
    '    $excel = New-Object -ComObject Excel.Application',
    '    $excel.Visible = $false',
    '    $excel.DisplayAlerts = $false',
    "    $wb = $excel.Workbooks.Open('" + psPath + "', 0, $true)",
    '    Start-Sleep -Seconds 1',
    '    $sheetCount = $wb.Worksheets.Count',
    '    $allText = ""',
    '    for ($s = 1; $s -le $sheetCount; $s++) {',
    '        $ws = $wb.Worksheets.Item($s)',
    '        $wsName = $ws.Name',
    '        $allText += "--- Sheet $s`: $wsName ---' + newline + '"',
    '        $usedRange = $ws.UsedRange',
    '        if ($usedRange -ne $null) {',
    '            $rowCount = $usedRange.Rows.Count',
    '            $colCount = $usedRange.Columns.Count',
    '            for ($r = 1; $r -le $rowCount; $r++) {',
    '                $rowText = ""',
    '                for ($c = 1; $c -le $colCount; $c++) {',
    '                    $cellVal = ""',
    '                    try {',
    '                        $cell = $usedRange.Cells.Item($r, $c)',
    '                        if ($cell.Value2 -ne $null) {',
    '                            $cellVal = [string]$cell.Value2',
    '                        }',
    '                    } catch { }',
    '                    if ($c -gt 1) { $rowText += "`t" }',
    '                    $rowText += $cellVal',
    '                }',
    '                $allText += $rowText + "' + newline + '"',
    '            }',
    '        }',
    '        $allText += "' + newline + '"',
    '    }',
    '    Write-Output "STATS:$sheetCount"',
    '    Write-Output "TEXT_START"',
    '    Write-Output $allText',
    '    Write-Output "TEXT_END"',
    '} catch {',
    '    Write-Error $_.Exception.Message',
    '    exit 1',
    '} finally {',
    '    if ($wb) {',
    '        $wb.Close($false)',
    '        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($wb) | Out-Null',
    '    }',
    '    if ($excel) {',
    '        $excel.Quit()',
    '        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null',
    '    }',
    '    [System.GC]::Collect()',
    '    [System.GC]::WaitForPendingFinalizers()',
    '}',
  ].join('\n');
}
