# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  # Members with Maintain permission are centralized here
  - member: yanhu
    role: Maintain
  - member: yanhu
    role: Maintain
  - member: lunzhang
    role: Maintain
  - member: jshang
    role: Maintain
  - member: jshang
    role: Maintain
  - member: lunzhang
    role: Maintain
  
  # All other members have Write access
  - member: dingxiao
    role: Write
  - member: menghuihu
    role: Write
  - member: jianliwei
    role: Write
  - member: v-yunn
    role: Write
  - member: jiamingmao
    role: Write
  - member: juntongliu
    role: Write
  - member: jianlin1
    role: Write
  - member: sezho
    role: Write
  - member: alexyuan
    role: Write
  - member: emilywu
    role: Write
  - member: hongjunqiu
    role: Write
  - member: gao.jie
    role: Write
  - member: juanliu
    role: Write
  - member: kashe
    role: Write
  - member: lingyanzhao
    role: Write
  - member: jinghuama
    role: Write
  - member: mile
    role: Write
  - member: lmike
    role: Write
  - member: shengjieshi
    role: Write
  - member: siyangliu
    role: Write
  - member: yche
    role: Write
  - member: yancheng
    role: Write
  - member: angliu
    role: Write
  - member: yongweizhang
    role: Write
  - member: eviema
    role: Write
  - member: jie.tang
    role: Write
  - member: liyayong
    role: Write
  - member: xiaoxch
    role: Write
  - member: huitingchen
    role: Write
  - member: ruicheng
    role: Write
  - member: wej
    role: Write
  - member: xiaochunzhao
    role: Write
  - member: jianjunchen
    role: Write
  - member: danielchen
    role: Write
  - member: menci
    role: Write
  - member: zhouweiwei
    role: Write
  - member: xanzh
    role: Write
  - member: wuyin
    role: Write
  - member: neilbao
    role: Write
  - member: qunmi
    role: Write
  - member: kunwang
    role: Write
  - member: manyang
    role: Write
  - member: qikaizhong
    role: Write
  - member: yhe
    role: Write
  - member: toyu
    role: Write
  - member: yuexiong
    role: Write
  - member: zhengdawang
    role: Write
  - member: wenxyang
    role: Write
  - member: keqli
    role: Write
  - member: yutongzhu
    role: Write
  - member: zhizhen
    role: Write
  - member: yueyingchen
    role: Write
  - member: yuanjunzhu
    role: Write
  - member: changliu1
    role: Write
  - member: jiayuchen
    role: Write
  - member: yuewang1
    role: Write
  - member: wuqiang
    role: Write
  - member: yazho
    role: Write
  - member: yueliu1
    role: Write
  - member: zhenyushan
    role: Write
  - member: zhuoyuqian
    role: Write
  - member: pengyuanwang
    role: Write
  - member: zhengyixu
    role: Write
  - member: cheyan
    role: Write
  - member: jiajunyan
    role: Write
  - member: leescott
    role: Write
  - member: jiayiyan
    role: Write
  - member: zhangjingwei
    role: Write
  - member: yazhouzhou
    role: Write
  - member: liangzeng
    role: Write
  - member: chfen
    role: Write
  - member: quns
    role: Write
  - member: yuanjunzhudir
    role: Write
  - member: jianjun-fte
    role: Write
  - member: cogao
    role: Write
  - member: liujingping
    role: Write
