/**
 * Pure validation, normalization, and projection helpers for the Agent Hooks
 * IPC surface (tech-doc §13). Kept free of Electron/IO so every branch is unit
 * testable, and so the IPC registrar stays a thin orchestrator.
 *
 * The renderer is never trusted: command actions are screened with the shared
 * `validateHookCommand` policy, sizes are bounded, matcher regexes are compile
 * checked, and identity/timestamps are generated by the caller (main), not the
 * renderer.
 */

import type {
  AgentHookEvent,
  CommandHookAction,
  HookAction,
  HttpHookAction,
  HttpHookMethod,
} from './types';
import {
  MAX_HOOK_HTTP_BODY_LENGTH,
  MAX_HOOK_HTTP_HEADER_CHARS,
  MAX_HOOK_HTTP_HEADERS,
  MAX_HOOK_IF_LENGTH,
  MAX_HOOK_TIMEOUT_MS,
} from './types';
import { validateHookCommand } from './commandHookRunner';
import { validateHookUrl } from './httpHookRunner';

export const MAX_HOOK_NAME_LENGTH = 200;
export const MAX_HOOK_DESCRIPTION_LENGTH = 2000;
export const MAX_HOOK_MATCHER_LENGTH = 500;
export const MIN_HOOK_TIMEOUT_MS = 100;
export {
  MAX_HOOK_IF_LENGTH,
  MAX_HOOK_TIMEOUT_MS,
};
export const MIN_HOOK_TIMEOUT_SECONDS = MIN_HOOK_TIMEOUT_MS / 1000;
export const MAX_HOOK_TIMEOUT_SECONDS = MAX_HOOK_TIMEOUT_MS / 1000;
export const MAX_HOOK_URL_LENGTH = 2048;
export {
  MAX_HOOK_HTTP_BODY_LENGTH,
  MAX_HOOK_HTTP_HEADER_CHARS,
  MAX_HOOK_HTTP_HEADERS,
};

const VALID_EVENTS: ReadonlySet<AgentHookEvent> = new Set<AgentHookEvent>([
  'SessionStart',
  'UserPromptSubmit',
  'PreToolUse',
  'PostToolUse',
  'PostToolUseFailure',
  'Stop',
  'PreCompact',
  'PostCompact',
]);

const VALID_HTTP_METHODS: ReadonlySet<HttpHookMethod> = new Set<HttpHookMethod>([
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
]);

/** Normalized, persistable shape of a create/update Hook payload. */
export interface NormalizedHookInput {
  name: string;
  description?: string;
  enabled: boolean;
  event: AgentHookEvent;
  matcher?: string;
  action: HookAction;
}

export type Ok<T> = { ok: true; value: T };
export type Err = { ok: false; error: string };
export type Result<T> = Ok<T> | Err;

const ok = <T>(value: T): Ok<T> => ({ ok: true, value });
const err = (error: string): Err => ({ ok: false, error });

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function validateName(raw: unknown): Result<string> {
  if (typeof raw !== 'string') return err('Hook name is required');
  const trimmed = raw.trim();
  if (trimmed.length === 0) return err('Hook name is required');
  if (trimmed.length > MAX_HOOK_NAME_LENGTH) {
    return err(`Hook name exceeds ${MAX_HOOK_NAME_LENGTH} characters`);
  }
  return ok(trimmed);
}

function validateDescription(raw: unknown): Result<string | undefined> {
  if (raw === undefined) return ok(undefined);
  if (typeof raw !== 'string') return err('Hook description must be a string');
  if (raw.length > MAX_HOOK_DESCRIPTION_LENGTH) {
    return err(`Hook description exceeds ${MAX_HOOK_DESCRIPTION_LENGTH} characters`);
  }
  return ok(raw);
}

function validateTimeoutMs(raw: unknown): Result<number | undefined> {
  if (raw === undefined) return ok(undefined);
  if (typeof raw !== 'number' || !Number.isFinite(raw)) {
    return err('Hook timeoutMs must be a number');
  }
  if (raw < MIN_HOOK_TIMEOUT_MS || raw > MAX_HOOK_TIMEOUT_MS) {
    return err(`Hook timeoutMs must be between ${MIN_HOOK_TIMEOUT_MS} and ${MAX_HOOK_TIMEOUT_MS}`);
  }
  return ok(raw);
}

function validateTimeoutSeconds(raw: unknown): Result<number | undefined> {
  if (raw === undefined) return ok(undefined);
  if (typeof raw !== 'number' || !Number.isFinite(raw)) {
    return err('Hook timeout must be a number of seconds');
  }
  if (raw < MIN_HOOK_TIMEOUT_SECONDS || raw > MAX_HOOK_TIMEOUT_SECONDS) {
    return err(`Hook timeout must be between ${MIN_HOOK_TIMEOUT_SECONDS} and ${MAX_HOOK_TIMEOUT_SECONDS} seconds`);
  }
  return ok(raw);
}

function validateArgs(raw: unknown): Result<string[] | undefined> {
  if (raw === undefined) return ok(undefined);
  if (!Array.isArray(raw)) return err('Hook args must be an array');
  if (!raw.every(entry => typeof entry === 'string')) {
    return err('Hook args entries must be strings');
  }
  return ok([...raw]);
}

function validateIf(raw: unknown): Result<string | undefined> {
  if (raw === undefined) return ok(undefined);
  if (typeof raw !== 'string') return err('Hook if must be a string');
  const trimmed = raw.trim();
  if (trimmed === '') return ok(undefined);
  if (trimmed.length > MAX_HOOK_IF_LENGTH) {
    return err(`Hook if exceeds ${MAX_HOOK_IF_LENGTH} characters`);
  }
  return ok(trimmed);
}

function applyTimeoutFields(
  raw: Record<string, unknown>,
  action: CommandHookAction | HttpHookAction,
): Result<void> {
  const timeoutResult = validateTimeoutSeconds(raw.timeout);
  if (!timeoutResult.ok) return timeoutResult;
  if (timeoutResult.value !== undefined) {
    action.timeout = timeoutResult.value;
    return ok(undefined);
  }

  const timeoutMsResult = validateTimeoutMs(raw.timeoutMs);
  if (!timeoutMsResult.ok) return timeoutMsResult;
  if (timeoutMsResult.value !== undefined) action.timeoutMs = timeoutMsResult.value;
  return ok(undefined);
}

function validateCommandAction(raw: Record<string, unknown>): Result<CommandHookAction> {
  if (typeof raw.command !== 'string' || raw.command.trim().length === 0) {
    return err('Hook command is required');
  }
  const argsResult = validateArgs(raw.args);
  if (!argsResult.ok) return argsResult;

  const commandError = validateHookCommand(raw.command, argsResult.value);
  if (commandError) return err(commandError);

  const action: CommandHookAction = { type: 'command', command: raw.command };
  if (argsResult.value !== undefined) action.args = argsResult.value;

  const ifResult = validateIf(raw.if);
  if (!ifResult.ok) return ifResult;
  if (ifResult.value !== undefined) action.if = ifResult.value;

  const timeoutResult = applyTimeoutFields(raw, action);
  if (!timeoutResult.ok) return timeoutResult;

  if (raw.async !== undefined) {
    if (typeof raw.async !== 'boolean') return err('Hook async must be a boolean');
    action.async = raw.async;
  }

  return ok(action);
}

function validateHttpAction(raw: Record<string, unknown>): Result<HttpHookAction> {
  if (typeof raw.url !== 'string' || raw.url.trim().length === 0) {
    return err('Hook url is required');
  }
  if (raw.url.length > MAX_HOOK_URL_LENGTH) {
    return err(`Hook url exceeds ${MAX_HOOK_URL_LENGTH} characters`);
  }
  const urlError = validateHookUrl(raw.url);
  if (urlError) return err(urlError);

  const action: HttpHookAction = { type: 'http', url: raw.url };

  const ifResult = validateIf(raw.if);
  if (!ifResult.ok) return ifResult;
  if (ifResult.value !== undefined) action.if = ifResult.value;

  if (raw.method !== undefined) {
    if (typeof raw.method !== 'string' || !VALID_HTTP_METHODS.has(raw.method as HttpHookMethod)) {
      return err('Hook method is invalid');
    }
    action.method = raw.method as HttpHookMethod;
  }

  if (raw.headers !== undefined) {
    if (!isPlainObject(raw.headers)) return err('Hook headers must be an object');
    const entries = Object.entries(raw.headers);
    if (entries.length > MAX_HOOK_HTTP_HEADERS) {
      return err(`Hook headers exceed ${MAX_HOOK_HTTP_HEADERS} entries`);
    }
    const headers: Record<string, string> = {};
    let headerChars = 0;
    for (const [key, value] of entries) {
      if (typeof value !== 'string') return err('Hook header values must be strings');
      headerChars += key.length + value.length;
      if (headerChars > MAX_HOOK_HTTP_HEADER_CHARS) {
        return err(`Hook headers exceed ${MAX_HOOK_HTTP_HEADER_CHARS} characters`);
      }
      headers[key] = value;
    }
    if (entries.length > 0) action.headers = headers;
  }

  if (raw.body !== undefined) {
    if (typeof raw.body !== 'string') return err('Hook body must be a string');
    if (raw.body.length > MAX_HOOK_HTTP_BODY_LENGTH) {
      return err(`Hook body exceeds ${MAX_HOOK_HTTP_BODY_LENGTH} characters`);
    }
    action.body = raw.body;
  }

  const timeoutResult = applyTimeoutFields(raw, action);
  if (!timeoutResult.ok) return timeoutResult;

  if (raw.async !== undefined) {
    if (typeof raw.async !== 'boolean') return err('Hook async must be a boolean');
    action.async = raw.async;
  }

  return ok(action);
}

function validateAction(raw: unknown): Result<HookAction> {
  if (!isPlainObject(raw)) return err('Hook action must be an object');
  if (raw.type === 'command') return validateCommandAction(raw);
  if (raw.type === 'http') return validateHttpAction(raw);
  return err('Only command and http Hook actions are supported');
}

function validateMatcherString(raw: unknown): Result<string | undefined> {
  if (raw === undefined) return ok(undefined);
  if (typeof raw !== 'string') return err('Hook matcher must be a string');
  if (raw.length > MAX_HOOK_MATCHER_LENGTH) {
    return err(`Hook matcher exceeds ${MAX_HOOK_MATCHER_LENGTH} characters`);
  }
  const trimmed = raw.trim();
  if (trimmed === '' || trimmed === '*') return ok(raw);
  try {
    // The runtime evaluates non-exact matcher patterns as JavaScript regular
    // expressions; treat anything that successfully parses as RegExp as valid.
    void new RegExp(trimmed);
  } catch {
    return err('Hook matcher is not a valid pattern');
  }
  return ok(raw);
}

function validateEvent(raw: unknown): Result<AgentHookEvent> {
  if (typeof raw !== 'string' || !VALID_EVENTS.has(raw as AgentHookEvent)) {
    return err('Hook event is invalid');
  }
  return ok(raw as AgentHookEvent);
}

function validateEnabled(raw: unknown, fallback: boolean): Result<boolean> {
  if (raw === undefined) return ok(fallback);
  if (typeof raw !== 'boolean') return err('Hook enabled must be a boolean');
  return ok(raw);
}

/** Validate and normalize a create-Hook payload into a persistable shape. */
export function validateCreateHookInput(input: unknown): Result<NormalizedHookInput> {
  if (!isPlainObject(input)) return err('Hook input is required');

  const nameResult = validateName(input.name);
  if (!nameResult.ok) return nameResult;

  const descriptionResult = validateDescription(input.description);
  if (!descriptionResult.ok) return descriptionResult;

  const enabledResult = validateEnabled(input.enabled, false);
  if (!enabledResult.ok) return enabledResult;

  const eventResult = validateEvent(input.event);
  if (!eventResult.ok) return eventResult;

  const matcherResult = validateMatcherString(input.matcher);
  if (!matcherResult.ok) return matcherResult;

  const actionResult = validateAction(input.action);
  if (!actionResult.ok) return actionResult;

  const normalized: NormalizedHookInput = {
    name: nameResult.value,
    enabled: false,
    event: eventResult.value,
    action: actionResult.value,
  };
  if (descriptionResult.value !== undefined) normalized.description = descriptionResult.value;
  if (matcherResult.value !== undefined) normalized.matcher = matcherResult.value;
  return ok(normalized);
}

/** Validate and normalize an update-Hook patch; only present keys are returned. */
export function validateUpdateHookPatch(patch: unknown): Result<Partial<NormalizedHookInput>> {
  if (!isPlainObject(patch)) return err('Hook patch is required');

  const result: Partial<NormalizedHookInput> = {};

  if ('name' in patch) {
    const nameResult = validateName(patch.name);
    if (!nameResult.ok) return nameResult;
    result.name = nameResult.value;
  }

  if ('description' in patch) {
    const descriptionResult = validateDescription(patch.description);
    if (!descriptionResult.ok) return descriptionResult;
    result.description = descriptionResult.value;
  }

  if ('enabled' in patch) {
    const enabledResult = validateEnabled(patch.enabled, true);
    if (!enabledResult.ok) return enabledResult;
    result.enabled = enabledResult.value;
  }

  if ('event' in patch) {
    const eventResult = validateEvent(patch.event);
    if (!eventResult.ok) return eventResult;
    result.event = eventResult.value;
  }

  if ('matcher' in patch) {
    const matcherResult = validateMatcherString(patch.matcher);
    if (!matcherResult.ok) return matcherResult;
    result.matcher = matcherResult.value;
  }

  if ('action' in patch) {
    const actionResult = validateAction(patch.action);
    if (!actionResult.ok) return actionResult;
    result.action = actionResult.value;
  }

  return ok(result);
}
